package de.bund.bsi.ecard.api._1;

import iso.std.iso_iec._24727.tech.schema.RequestType;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 */
@WebService(name = "Management", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
//    org.w3._2001._04.xmldsig_more_.ObjectFactory.class,
		de.bund.bsi.ecard.api._1.ObjectFactory.class,
		//    oasis.names.tc.saml._2_0.assertion.ObjectFactory.class,
		//    oasis.names.tc.dss_x._1_0.profiles.verificationreport.schema_.ObjectFactory.class,
		//    org.etsi.uri._02231.v2.ObjectFactory.class,
		//    org.etsi.uri._02231.v2_1.ObjectFactory.class,
		iso.std.iso_iec._24727.tech.schema.ObjectFactory.class,
//    org.etsi.uri._01903.v1_3.ObjectFactory.class,
//    org.w3._2001._04.xmlenc_.ObjectFactory.class,
//    org.setcce.schemas.ers.ObjectFactory.class,
//    oasis.names.tc.saml._1_0.assertion.ObjectFactory.class
})
public interface Management {

	/**
	 * @param parameters
	 * @return returns de.bund.bsi.ecard.api._1.InitializeFrameworkResponse
	 */
	@WebMethod(operationName = "InitializeFramework", action = "http://www.bsi.bund.de/ecard/api/1.0#InitializeFramework")
	@WebResult(name = "InitializeFrameworkResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
	public InitializeFrameworkResponse initializeFramework(
			@WebParam(name = "InitializeFramework", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters") RequestType parameters);

}
