
package iso.std.iso_iec._24727.tech.schema;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SAL", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", wsdlLocation = "file:/C:/Development/workspace/eCard-API-1.1.2/schemas/ISO24727-3.wsdl")
public class SAL_Service
    extends Service
{

    private final static URL SAL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(iso.std.iso_iec._24727.tech.schema.SAL_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = iso.std.iso_iec._24727.tech.schema.SAL_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Development/workspace/eCard-API-1.1.2/schemas/ISO24727-3.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Development/workspace/eCard-API-1.1.2/schemas/ISO24727-3.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SAL_WSDL_LOCATION = url;
    }

    public SAL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAL_Service() {
        super(SAL_WSDL_LOCATION, new QName("urn:iso:std:iso-iec:24727:tech:schema", "SAL"));
    }

    /**
     * 
     * @return
     *     returns SAL
     */
    @WebEndpoint(name = "SALPort")
    public SAL getSALPort() {
        return super.getPort(new QName("urn:iso:std:iso-iec:24727:tech:schema", "SALPort"), SAL.class);
    }

}
