
package iso.std.iso_iec._24727.tech.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ISO24727-Protocols", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ISO24727Protocols {


    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.TCAPIOpenResponse
     */
    @WebMethod(operationName = "TC_API_Open", action = "urn:iso:std:iso-iec:24727:tech:schema:TC_API_Open")
    @WebResult(name = "TC_API_OpenResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public TCAPIOpenResponse tcAPIOpen(
        @WebParam(name = "TC_API_Open", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        TCAPIOpen parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "TC_API_Close", action = "urn:iso:std:iso-iec:24727:tech:schema:TC_API_Close")
    @WebResult(name = "TC_API_CloseResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ResponseType tcAPIClose(
        @WebParam(name = "TC_API_Close", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        TCAPIClose parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "StartPAOS", action = "urn:iso:std:iso-iec:24727:tech:schema:StartPAOS")
    @WebResult(name = "StartPAOSResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ResponseType startPAOS(
        @WebParam(name = "StartPAOS", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        StartPAOS parameters);

}
