
package de.bund.bsi.ecard.api._1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Management", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", wsdlLocation = "file:/C:/Development/workspace/eCard-API-1.1.2/schemas/Management.wsdl")
public class Management_Service
    extends Service
{

    private final static URL MANAGEMENT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.bund.bsi.ecard.api._1.Management_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.bund.bsi.ecard.api._1.Management_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Development/workspace/eCard-API-1.1.2/schemas/Management.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Development/workspace/eCard-API-1.1.2/schemas/Management.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANAGEMENT_WSDL_LOCATION = url;
    }

    public Management_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Management_Service() {
        super(MANAGEMENT_WSDL_LOCATION, new QName("http://www.bsi.bund.de/ecard/api/1.1", "Management"));
    }

    /**
     * 
     * @return
     *     returns Management
     */
    @WebEndpoint(name = "ManagementPort")
    public Management getManagementPort() {
        return super.getPort(new QName("http://www.bsi.bund.de/ecard/api/1.1", "ManagementPort"), Management.class);
    }

}
