
package iso.std.iso_iec._24727.tech.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IFD", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IFD {


    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.EstablishContextResponse
     */
    @WebMethod(operationName = "EstablishContext", action = "urn:iso:std:iso-iec:24727:tech:schema:EstablishContext")
    @WebResult(name = "EstablishContextResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public EstablishContextResponse establishContext(
        @WebParam(name = "EstablishContext", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        EstablishContext parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "ReleaseContext", action = "urn:iso:std:iso-iec:24727:tech:schema:ReleaseContext")
    @WebResult(name = "ReleaseContextResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ResponseType releaseContext(
        @WebParam(name = "ReleaseContext", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        ReleaseContext parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ListIFDsResponse
     */
    @WebMethod(operationName = "ListIFDs", action = "urn:iso:std:iso-iec:24727:tech:schema:ListIFDs")
    @WebResult(name = "ListIFDsResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ListIFDsResponse listIFDs(
        @WebParam(name = "ListIFDs", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        ListIFDs parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.GetIFDCapabilitiesResponse
     */
    @WebMethod(operationName = "GetIFDCapabilities", action = "urn:iso:std:iso-iec:24727:tech:schema:GetIFDCapabilities")
    @WebResult(name = "GetIFDCapabilitiesResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public GetIFDCapabilitiesResponse getIFDCapabilities(
        @WebParam(name = "GetIFDCapabilities", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        GetIFDCapabilities parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.GetStatusResponse
     */
    @WebMethod(operationName = "GetStatus", action = "urn:iso:std:iso-iec:24727:tech:schema:GetStatus")
    @WebResult(name = "GetStatusResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public GetStatusResponse getStatus(
        @WebParam(name = "GetStatus", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        GetStatus parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.WaitResponse
     */
    @WebMethod(operationName = "Wait", action = "urn:iso:std:iso-iec:24727:tech:schema:Wait")
    @WebResult(name = "WaitResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public WaitResponse wait(
        @WebParam(name = "Wait", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        Wait parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "Cancel", action = "urn:iso:std:iso-iec:24727:tech:schema:Cancel")
    @WebResult(name = "CancelResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ResponseType cancel(
        @WebParam(name = "Cancel", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        Cancel parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ControlIFDResponse
     */
    @WebMethod(operationName = "ControlIFD", action = "urn:iso:std:iso-iec:24727:tech:schema:ControlIFD")
    @WebResult(name = "ControlIFDResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ControlIFDResponse controlIFD(
        @WebParam(name = "ControlIFD", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        ControlIFD parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ConnectResponse
     */
    @WebMethod(operationName = "Connect", action = "urn:iso:std:iso-iec:24727:tech:schema:Connect")
    @WebResult(name = "ConnectResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ConnectResponse connect(
        @WebParam(name = "Connect", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        Connect parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "Disconnect", action = "urn:iso:std:iso-iec:24727:tech:schema:Disconnect")
    @WebResult(name = "DisconnectResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ResponseType disconnect(
        @WebParam(name = "Disconnect", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        Disconnect parameters);

    /**
     * 
     * @param beginTransaction
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "BeginTransaction", action = "urn:iso:std:iso-iec:24727:tech:schema:BeginTransaction")
    @WebResult(name = "BeginTransactionResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "BeginTransactionResponse")
    public ResponseType beginTransaction(
        @WebParam(name = "BeginTransaction", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "BeginTransaction")
        BeginTransaction beginTransaction);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "EndTransaction", action = "urn:iso:std:iso-iec:24727:tech:schema:EndTransaction")
    @WebResult(name = "EndTransactionResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ResponseType endTransaction(
        @WebParam(name = "EndTransaction", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        EndTransaction parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.TransmitResponse
     */
    @WebMethod(operationName = "Transmit", action = "urn:iso:std:iso-iec:24727:tech:schema:Transmit")
    @WebResult(name = "TransmitResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public TransmitResponse transmit(
        @WebParam(name = "Transmit", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        Transmit parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.VerifyUserResponse
     */
    @WebMethod(operationName = "VerifyUser", action = "urn:iso:std:iso-iec:24727:tech:schema:VerifyUser")
    @WebResult(name = "VerifyUserResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public VerifyUserResponse verifyUser(
        @WebParam(name = "VerifyUser", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        VerifyUser parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ModifyVerificationDataResponse
     */
    @WebMethod(operationName = "ModifyVerificationData", action = "urn:iso:std:iso-iec:24727:tech:schema:ModifyVerificationData")
    @WebResult(name = "ModifyVerificationDataResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ModifyVerificationDataResponse modifyVerificationData(
        @WebParam(name = "ModifyVerificationData", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        ModifyVerificationData parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "Output", action = "urn:iso:std:iso-iec:24727:tech:schema:Output")
    @WebResult(name = "OutputResponse", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
    public ResponseType output(
        @WebParam(name = "Output", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", partName = "parameters")
        Output parameters);

}
