
package iso.std.iso_iec._24727.tech.schema;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "IFD", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", wsdlLocation = "file:/C:/Development/workspace/eCard-API-1.1.2/schemas/ISOIFD.wsdl")
public class IFD_Service
    extends Service
{

    private final static URL IFD_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(iso.std.iso_iec._24727.tech.schema.IFD_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = iso.std.iso_iec._24727.tech.schema.IFD_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Development/workspace/eCard-API-1.1.2/schemas/ISOIFD.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Development/workspace/eCard-API-1.1.2/schemas/ISOIFD.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IFD_WSDL_LOCATION = url;
    }

    public IFD_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IFD_Service() {
        super(IFD_WSDL_LOCATION, new QName("urn:iso:std:iso-iec:24727:tech:schema", "IFD"));
    }

    /**
     * 
     * @return
     *     returns IFD
     */
    @WebEndpoint(name = "IFDPort")
    public IFD getIFDPort() {
        return super.getPort(new QName("urn:iso:std:iso-iec:24727:tech:schema", "IFDPort"), IFD.class);
    }

}
