
package iso.std.iso_iec._24727.tech.schema;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ISO24727-Protocols", targetNamespace = "urn:iso:std:iso-iec:24727:tech:schema", wsdlLocation = "file:/C:/Development/workspace/eCard-API-1.1.2/schemas/ISO24727-Protocols.wsdl")
public class ISO24727Protocols_Service
    extends Service
{

    private final static URL ISO24727PROTOCOLS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(iso.std.iso_iec._24727.tech.schema.ISO24727Protocols_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = iso.std.iso_iec._24727.tech.schema.ISO24727Protocols_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Development/workspace/eCard-API-1.1.2/schemas/ISO24727-Protocols.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Development/workspace/eCard-API-1.1.2/schemas/ISO24727-Protocols.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ISO24727PROTOCOLS_WSDL_LOCATION = url;
    }

    public ISO24727Protocols_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISO24727Protocols_Service() {
        super(ISO24727PROTOCOLS_WSDL_LOCATION, new QName("urn:iso:std:iso-iec:24727:tech:schema", "ISO24727-Protocols"));
    }

    /**
     * 
     * @return
     *     returns ISO24727Protocols
     */
    @WebEndpoint(name = "ISO24727-ProtocolsPort")
    public ISO24727Protocols getISO24727ProtocolsPort() {
        return super.getPort(new QName("urn:iso:std:iso-iec:24727:tech:schema", "ISO24727-ProtocolsPort"), ISO24727Protocols.class);
    }

}
