//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.12 at 02:29:27 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:liberty:paos:2006-08", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package liberty.paos._2006_08;
