
package de.bund.bsi.ecard.api._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import iso.std.iso_iec._24727.tech.schema.RequestType;
import iso.std.iso_iec._24727.tech.schema.ResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Management", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Management {


    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.InitializeFrameworkResponse
     */
    @WebMethod(operationName = "InitializeFramework", action = "http://www.bsi.bund.de/ecard/api/1.0#InitializeFramework")
    @WebResult(name = "InitializeFrameworkResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public InitializeFrameworkResponse initializeFramework(
        @WebParam(name = "InitializeFramework", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        RequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "TerminateFramework", action = "http://www.bsi.bund.de/ecard/api/1.0#TerminateFramework")
    @WebResult(name = "TerminateFrameworkResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType terminateFramework(
        @WebParam(name = "TerminateFramework", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        RequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.APIACLListResponse
     */
    @WebMethod(operationName = "APIACLList", action = "http://www.bsi.bund.de/ecard/api/1.0#APIACLList")
    @WebResult(name = "APIACLListResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public APIACLListResponse apiaclList(
        @WebParam(name = "APIACLList", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        APIACLList parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "APIACLModify", action = "http://www.bsi.bund.de/ecard/api/1.0#APIACLModify")
    @WebResult(name = "APIACLModifyResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType apiaclModify(
        @WebParam(name = "APIACLModify", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        APIACLModify parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "FrameworkUpdate", action = "http://www.bsi.bund.de/ecard/api/1.0#FrameworkUpdate")
    @WebResult(name = "FrameworkUpdateResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType frameworkUpdate(
        @WebParam(name = "FrameworkUpdate", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        RequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.GetDefaultParametersResponse
     */
    @WebMethod(operationName = "GetDefaultParameters", action = "http://www.bsi.bund.de/ecard/api/1.0#GetDefaultParameters")
    @WebResult(name = "GetDefaultParametersResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public GetDefaultParametersResponse getDefaultParameters(
        @WebParam(name = "GetDefaultParameters", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        GetDefaultParameters parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "SetDefaultParameters", action = "http://www.bsi.bund.de/ecard/api/1.0#SetDefaultParameters")
    @WebResult(name = "SetDefaultParametersResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType setDefaultParameters(
        @WebParam(name = "SetDefaultParameters", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        SetDefaultParameters parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.GetCardInfoListResponse
     */
    @WebMethod(operationName = "GetCardInfoList", action = "http://www.bsi.bund.de/ecard/api/1.0#GetCardInfoList")
    @WebResult(name = "GetCardInfoListResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public GetCardInfoListResponse getCardInfoList(
        @WebParam(name = "GetCardInfoList", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        GetCardInfoList parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "SetCardInfoList", action = "http://www.bsi.bund.de/ecard/api/1.0#SetCardInfoList")
    @WebResult(name = "SetCardInfoListResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType setCardInfoList(
        @WebParam(name = "SetCardInfoList", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        SetCardInfoList parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "AddCardInfoFiles", action = "http://www.bsi.bund.de/ecard/api/1.0#AddCardInfoFiles")
    @WebResult(name = "AddCardInfoFilesResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType addCardInfoFiles(
        @WebParam(name = "AddCardInfoFiles", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        AddCardInfoFiles parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "DeleteCardInfoFiles", action = "http://www.bsi.bund.de/ecard/api/1.0#DeleteCardInfoFiles")
    @WebResult(name = "DeleteCardInfoFilesResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType deleteCardInfoFiles(
        @WebParam(name = "DeleteCardInfoFiles", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        DeleteCardInfoFiles parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "RegisterIFD", action = "http://www.bsi.bund.de/ecard/api/1.0#RegisterIFD")
    @WebResult(name = "RegisterIFDResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType registerIFD(
        @WebParam(name = "RegisterIFD", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        RegisterIFD parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "UnregisterIFD", action = "http://www.bsi.bund.de/ecard/api/1.0#UnregisterIFD")
    @WebResult(name = "UnregisterIFDResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType unregisterIFD(
        @WebParam(name = "UnregisterIFD", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        UnregisterIFD parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.GetTrustedViewerListResponse
     */
    @WebMethod(operationName = "GetTrustedViewerList", action = "http://www.bsi.bund.de/ecard/api/1.0#GetTrustedViewerList")
    @WebResult(name = "GetTrustedViewerListResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public GetTrustedViewerListResponse getTrustedViewerList(
        @WebParam(name = "GetTrustedViewerList", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        GetTrustedViewerList parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.GetTrustedViewerConfigurationResponse
     */
    @WebMethod(operationName = "GetTrustedViewerConfiguration", action = "http://www.bsi.bund.de/ecard/api/1.0#GetTrustedViewerConfiguration")
    @WebResult(name = "GetTrustedViewerConfigurationResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public GetTrustedViewerConfigurationResponse getTrustedViewerConfiguration(
        @WebParam(name = "GetTrustedViewerConfiguration", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        GetTrustedViewerConfiguration parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "SetTrustedViewerConfiguration", action = "http://www.bsi.bund.de/ecard/api/1.0#SetTrustedViewerConfiguration")
    @WebResult(name = "SetTrustedViewerConfigurationResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType setTrustedViewerConfiguration(
        @WebParam(name = "SetTrustedViewerConfiguration", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        SetTrustedViewerConfiguration parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "AddTrustedViewer", action = "http://www.bsi.bund.de/ecard/api/1.0#AddTrustedViewer")
    @WebResult(name = "AddTrustedViewerResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType addTrustedViewer(
        @WebParam(name = "AddTrustedViewer", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        AddTrustedViewer parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "DeleteTrustedViewer", action = "http://www.bsi.bund.de/ecard/api/1.0#DeleteTrustedViewer")
    @WebResult(name = "DeleteTrustedViewerResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType deleteTrustedViewer(
        @WebParam(name = "DeleteTrustedViewer", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        DeleteTrustedViewer parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.GetTrustedIdentitiesResponse
     */
    @WebMethod(operationName = "GetTrustedIdentities", action = "http://www.bsi.bund.de/ecard/api/1.0#GetTrustedIdentities")
    @WebResult(name = "GetTrustedIdentitiesResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public GetTrustedIdentitiesResponse getTrustedIdentities(
        @WebParam(name = "GetTrustedIdentities", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        GetTrustedIdentities parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "AddTrustedCertificate", action = "http://www.bsi.bund.de/ecard/api/1.0#AddTrustedCertificate")
    @WebResult(name = "AddTrustedCertificateResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType addTrustedCertificate(
        @WebParam(name = "AddTrustedCertificate", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        AddTrustedCertificate parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "AddCertificate", action = "http://www.bsi.bund.de/ecard/api/1.0#AddCertificate")
    @WebResult(name = "AddCertificateResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType addCertificate(
        @WebParam(name = "AddCertificate", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        AddCertificate parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "DeleteCertificate", action = "http://www.bsi.bund.de/ecard/api/1.0#DeleteCertificate")
    @WebResult(name = "DeleteCertificateResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType deleteCertificate(
        @WebParam(name = "DeleteCertificate", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        DeleteCertificate parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "AddTSL", action = "http://www.bsi.bund.de/ecard/api/1.0#AddTSL")
    @WebResult(name = "AddTSLResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType addTSL(
        @WebParam(name = "AddTSL", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        AddTSL parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "DeleteTSL", action = "http://www.bsi.bund.de/ecard/api/1.0#DeleteTSL")
    @WebResult(name = "DeleteTSLResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType deleteTSL(
        @WebParam(name = "DeleteTSL", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        DeleteTSL parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.ExportTSLResponse
     */
    @WebMethod(operationName = "ExportTSL", action = "http://www.bsi.bund.de/ecard/api/1.0#ExportTSL")
    @WebResult(name = "ExportTSLResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ExportTSLResponse exportTSL(
        @WebParam(name = "ExportTSL", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        ExportTSL parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.ExportCertificateResponse
     */
    @WebMethod(operationName = "ExportCertificate", action = "http://www.bsi.bund.de/ecard/api/1.0#ExportCertificate")
    @WebResult(name = "ExportCertificateResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ExportCertificateResponse exportCertificate(
        @WebParam(name = "ExportCertificate", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        ExportCertificate parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.GetOCSPServicesResponse
     */
    @WebMethod(operationName = "GetOCSPServices", action = "http://www.bsi.bund.de/ecard/api/1.0#GetOCSPServices")
    @WebResult(name = "GetOCSPServicesResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public GetOCSPServicesResponse getOCSPServices(
        @WebParam(name = "GetOCSPServices", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        GetOCSPServices parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "SetOCSPServices", action = "http://www.bsi.bund.de/ecard/api/1.0#SetOCSPServices")
    @WebResult(name = "SetOCSPServicesResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType setOCSPServices(
        @WebParam(name = "SetOCSPServices", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        SetOCSPServices parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.GetDirectoryServicesResponse
     */
    @WebMethod(operationName = "GetDirectoryServices", action = "http://www.bsi.bund.de/ecard/api/1.0#GetDirectoryServices")
    @WebResult(name = "GetDirectoryServicesResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public GetDirectoryServicesResponse getDirectoryServices(
        @WebParam(name = "GetDirectoryServices", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        GetDirectoryServices parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "SetDirectoryServices", action = "http://www.bsi.bund.de/ecard/api/1.0#SetDirectoryServices")
    @WebResult(name = "SetDirectoryServicesResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType setDirectoryServices(
        @WebParam(name = "SetDirectoryServices", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        SetDirectoryServices parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns de.bund.bsi.ecard.api._1.GetTSServicesResponse
     */
    @WebMethod(operationName = "GetTSServices", action = "http://www.bsi.bund.de/ecard/api/1.0#GetTSServices")
    @WebResult(name = "GetTSServicesResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public GetTSServicesResponse getTSServices(
        @WebParam(name = "GetTSServices", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        GetTSServices parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns iso.std.iso_iec._24727.tech.schema.ResponseType
     */
    @WebMethod(operationName = "SetTSServices", action = "http://www.bsi.bund.de/ecard/api/1.0#SetTSServices")
    @WebResult(name = "SetTSServicesResponse", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
    public ResponseType setTSServices(
        @WebParam(name = "SetTSServices", targetNamespace = "http://www.bsi.bund.de/ecard/api/1.1", partName = "parameters")
        SetTSServices parameters);

}
