//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.12 at 02:29:27 AM MESZ 
//


package liberty.paos._2006_08;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the liberty.paos._2006_08 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceType_QNAME = new QName("urn:liberty:paos:2006-08", "ServiceType");
    private final static QName _PAOS_QNAME = new QName("urn:liberty:paos:2006-08", "PAOS");
    private final static QName _Options_QNAME = new QName("urn:liberty:paos:2006-08", "Options");
    private final static QName _EndpointReference_QNAME = new QName("urn:liberty:paos:2006-08", "EndpointReference");
    private final static QName _Address_QNAME = new QName("urn:liberty:paos:2006-08", "Address");
    private final static QName _MetaData_QNAME = new QName("urn:liberty:paos:2006-08", "MetaData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: liberty.paos._2006_08
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EndpointReferenceType }
     * 
     */
    public EndpointReferenceType createEndpointReferenceType() {
        return new EndpointReferenceType();
    }

    /**
     * Create an instance of {@link MetaDataType }
     * 
     */
    public MetaDataType createMetaDataType() {
        return new MetaDataType();
    }

    /**
     * Create an instance of {@link PaosType }
     * 
     */
    public PaosType createPaosType() {
        return new PaosType();
    }

    /**
     * Create an instance of {@link OptionsType }
     * 
     */
    public OptionsType createOptionsType() {
        return new OptionsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:liberty:paos:2006-08", name = "ServiceType")
    public JAXBElement<String> createServiceType(String value) {
        return new JAXBElement<String>(_ServiceType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaosType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:liberty:paos:2006-08", name = "PAOS")
    public JAXBElement<PaosType> createPAOS(PaosType value) {
        return new JAXBElement<PaosType>(_PAOS_QNAME, PaosType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:liberty:paos:2006-08", name = "Options")
    public JAXBElement<OptionsType> createOptions(OptionsType value) {
        return new JAXBElement<OptionsType>(_Options_QNAME, OptionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:liberty:paos:2006-08", name = "EndpointReference")
    public JAXBElement<EndpointReferenceType> createEndpointReference(EndpointReferenceType value) {
        return new JAXBElement<EndpointReferenceType>(_EndpointReference_QNAME, EndpointReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:liberty:paos:2006-08", name = "Address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:liberty:paos:2006-08", name = "MetaData")
    public JAXBElement<MetaDataType> createMetaData(MetaDataType value) {
        return new JAXBElement<MetaDataType>(_MetaData_QNAME, MetaDataType.class, null, value);
    }

}
